#
# Makefile for the focaltech touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-y += focaltech_upgrade_idc.o
obj-y += focaltech_upgrade_ft8716.o
obj-y += focaltech_upgrade_test.o
