ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy/
ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy/sensor
ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy/sensor/cci
ccflags-y += -Idrivers/misc/
obj-$(CONFIG_MSMB_CAMERA)   += msm_camera_cci_i2c.o msm_camera_qup_i2c.o msm_camera_spi.o msm_camera_dt_util.o msm_camera_tz_i2c.o

# daisy/sakura
ccflags-$(CONFIG_MACH_XIAOMI_SAKURA) += -Idrivers/media/platform/msm/camera_v2-legacy/sensor/io
ccflags-$(CONFIG_MACH_XIAOMI_DAISY) += -Idrivers/media/platform/msm/camera_v2-legacy/sensor/io
