#drivers/input/touchscreen/focaltech_touch/focaltech_test
#
#Makefile for test module
#



obj-y += focaltech_test.o
obj-y += focaltech_test_ini.o
obj-y += focaltech_test_detail_threshold.o
obj-y += supported_ic/

