#
# Makefile for the Synaptics DSX touchscreen driver.
#

# Each configuration option enables a list of files.

obj-y += synaptics_dsx_i2c.o
obj-y += synaptics_dsx_core.o
obj-y += synaptics_dsx_rmi_dev.o
obj-y += synaptics_dsx_fw_update.o
obj-y += synaptics_dsx_test_reporting.o
